# SQLite version 3.x
#   gem install postgresql
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'postgresql'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: xavy_development

test:
  <<: *default
  database: xavy_test

production:
  adapter: postgresql
  encoding: unicode
  username: xavy
  password: <%= ENV['XAVY_DATABASE_PASSWORD'] %>
  pool: 5
